### ISSUE TITLE
I need your help for hackintosh mac

### ISSUE THREAD

**Issue by lanhebe** [RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore#10]
I used your efi file to install Monterrey, but stuck on the black apple progress bar, please help and guide, thank you!

**Comment by RobyRew** [comment]
> I used your efi file to install Monterrey, but stuck on the black apple progress bar, please help and guide, thank you！

Disable Above4Gb... on bios

**Comment by lanhebe** [comment]
The above computer configuration can install the big sur system with your EFI file, but the sound is very small, and the graphics card amd rx590 cannot be driven.

**Comment by RobyRew** [comment]
in an hour I send you the Eli for your build wait

**Comment by RobyRew** [comment]
Ok I see that you have a different CPU and different GPU.

For the CPU you need to change the values on `config.plist > Kernel > Patch >` `Comment`...`cpuid_cores_per_package...`
`B8080000 0000`
`BA080000 0000`
`BA080000 0090`
With those modifications from the [AMD Kernel patch](https://github.com/AMD-OSX/AMD_Vanilla#read-me-first) you have full support for your Ryzen 7 3800X

Now moving on with GPU, you need to remove:
from `EFI > OC > ACPI`, SSDT-PLUG.aml (used for power management stuff for the GPU..)
from `EFI > OC > Kexts`, AGPMInjector.kext (Used for custom drivers on 5700XT)
from config.plist the respective sections for deleted items, and remove `agdpmod=pikera` and `applbkl=3` boot arguments from `config.plist > NVRAM > .. > boot-args`

If you find that the audio is not working you can search for an alternative layout for your audio card by testing different numbers within NVRAM boot-args with alcid=11, reboot test, alcid=12, reboot test, etc.

Here's latest EFI with these changes indicated applied, tell me if it worked:
[EFI.zip](https://github.com/RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore/files/9778850/EFI.zip)

**Comment by lanhebe** [comment]
> Ok I see that you have a different CPU and different GPU.
> 
> For the CPU you need to change the values on `config.plist > Kernel > Patch >` `Comment`...`cpuid_cores_per_package...` `B8080000 0000` `BA080000 0000` `BA080000 0090` With those modifications from the [AMD Kernel patch](https://github.com/AMD-OSX/AMD_Vanilla#read-me-first) you have full support for your Ryzen 7 3800X
> 
> Now moving on with GPU, you need to remove: from `EFI > OC > ACPI`, SSDT-PLUG.aml (used for power management stuff for the GPU..) from `EFI > OC > Kexts`, AGPMInjector.kext (Used for custom drivers on 5700XT) from config.plist the respective sections for deleted items, and remove `agdpmod=pikera` and `applbkl=3` boot arguments from `config.plist > NVRAM > .. > boot-args`
> 
> If you find that the audio is not working you can search for an alternative layout for your audio card by testing different numbers within NVRAM boot-args with alcid=11, reboot test, alcid=12, reboot test, etc.
> 
> Here's latest EFI with these changes indicated applied, tell me if it worked @lanhebe : [EFI.zip](https://github.com/RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore/files/9778850/EFI.zip)

Thank you very much!
![截屏2022-10-15 上午6 13 57](https://user-images.githubusercontent.com/5748516/195988334-4f901176-f3e0-4891-962c-082deef75165.png)
 I used the EFI file you packed for me to import. The Apple system big sur can normally enter the desktop and display cpu parameters, but the graphics card parameters cannot be displayed and driven. The amd rx590 gme is recognized by Apple as Radeon RX580 2048SP and cannot be driven. Can my video card amd rx590 gme imitate other video cards?

**Comment by RobyRew** [comment]
> but the graphics card parameters cannot be displayed and driven. The amd rx590 gme is recognized by Apple as Radeon RX580 2048SP and cannot be driven. Can my video card amd rx590 gme imitate other video cards?

Cn you explain more what is not being displayed and driven, like, what's wrong or not working?
GPU acceleration is not working correctly?

**Comment by qualchrone** [comment]
I also cannot boot with your EFI and always reboot, my cpu is 5950x with latest bios 7C37vHI

**Comment by RobyRew** [comment]
> I also cannot boot with your EFI and always reboot, my cpu is 5950x with latest bios 7C37vHI

Ok I see that you have a different CPU I don't know about de GPU, can you tell me about it??

For the CPU you need to change the values on `config.plist > Kernel > Patch >` `Comment`...`cpuid_cores_per_package...`
`B8100000 0000`
`BA100000 0000`
`BA100000 0090`
With those modifications from the [AMD Kernel patch](https://github.com/AMD-OSX/AMD_Vanilla#read-me-first) you have full support for your Ryzen 9 5950X

Be sure to have Above4G.. and Secure Boot Disabled on BIOS before booting the EFI otherwise you will not be able to boot at all.

Also if your GPU is different it will not work because I have loaded custom drivers for the 5700XT

Here's an EFI with your CPU patches I mentioned before applied: 
[EFI.zip](https://github.com/RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore/files/10202487/EFI.zip)

**Comment by qualchrone** [comment]
> 

I have 6900xt

**Comment by qualchrone** [comment]
> > I also cannot boot with your EFI and always reboot, my cpu is 5950x with latest bios 7C37vHI
> 
> Ok I see that you have a different CPU I don't know about de GPU, can you tell me about it??
> 
> For the CPU you need to change the values on `config.plist > Kernel > Patch >` `Comment`...`cpuid_cores_per_package...` `B8100000 0000` `BA100000 0000` `BA100000 0090` With those modifications from the [AMD Kernel patch](https://github.com/AMD-OSX/AMD_Vanilla#read-me-first) you have full support for your Ryzen 9 5950X
> 
> Be sure to have Above4G.. and Secure Boot Disabled on BIOS before booting the EFI otherwise you will not be able to boot at all.
> 
> Also if your GPU is different it will not work because I have loaded custom drivers for the 5700XT
> 
> Here's an EFI with your CPU patches I mentioned before applied: [EFI.zip](https://github.com/RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore/files/10202487/EFI.zip)

I tried this EFI, it still doesn't work
- use this efi checked
- disable above4g checked
- disable secure boot checked

**Comment by RobyRew** [comment]
> 
> > Here's an EFI with your CPU patches I mentioned before applied: [EFI.zip](https://github.com/RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore/files/10202487/EFI.zip)
> 
> 
> 
> I tried this EFI, it still doesn't work
> 
> - use this efi checked
> 
> - disable above4g checked
> 
> - disable secure boot checked

Can you activate verbose boot and show me where it fails?

to activate verbose boot and -v to nvram > boot arguments

**Comment by qualchrone** [comment]
This is the error 
![IMG_0402](https://user-images.githubusercontent.com/5027897/207468325-436ab67a-d7f3-4232-8fa3-ceb067bece79.jpg)

This is my slightly modified [EFI.zip](https://github.com/RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore/files/10222922/EFI.zip)

**Comment by RobyRew** [comment]
> This is my slightly modified [EFI.zip](https://github.com/RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore/files/10222922/EFI.zip)

Try now man!

**Comment by qualchrone** [comment]
> > This is my slightly modified [EFI.zip](https://github.com/RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore/files/10222922/EFI.zip)
> 
> Try now man!

I think your latest release has corrupt opencore. Even bootpicker not showing and directly boot to my 2nd drive

**Comment by RobyRew** [comment]
@qualchrone Okay, im so sorry for that, I forgot to enable bootpicker again, as I don't use other OS at the time.

Im gonna push an update to enable Bootpicker again, thank you too much!
Edit: Update done, the new EFI should be live now.

_for bluetooth, im not sure why is not working, since Fenvi T919 should be native_

**Comment by qualchrone** [comment]
> @qualchrone Okay, im so sorry for that, I forgot to enable bootpicker again, as I don't use other OS at the time.
> 
> Im gonna push an update to enable Bootpicker again, thank you too much! Edit: Update done, the new EFI should be live now.
> 
> _for bluetooth, im not sure why is not working, since Fenvi T919 should be native_

**Update:** 
My bluetooth works!!. Bluetooth was diasbled from windows, after I enable from windows and reboot to ventura voila everything works :)
