### ISSUE TITLE
missing docs/config.plist

### ISSUE THREAD

**Issue by fa1c0nx** [RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore#12]

**Comment by RobyRew** [comment]
it's not missing, that is an older template explaining what settings should be enabled and what DOES each thing, right now it's deleted because i didn't had the time to explain in detail everything, the real complete config.plis is on 
[/EFI/OC/config.plist](/EFI/OC/config.plist)

**Comment by fa1c0nx** [comment]
found it, sorry!
any idea if I could get it working on the following?

Motherboard: | MSI MAG x570 Tomahawk WiFi
CPU: | AMD Ryzen 9 5900X
GPU: | NVIDIA GeForce 3070

**Comment by RobyRew** [comment]
> found it, sorry!
> 
> any idea if I could get it working on the following?
> 
> 
> 
> Motherboard: | MSI MAG x570 Tomahawk WiFi
> 
> CPU: | AMD Ryzen 9 5900X
> 
> GPU: | NVIDIA GeForce 3070
> 

Sadly your GPU is not compatible with macOS you need any AMD GPU to be able to have image.

PS: motherboard and CPU are compatible with macOS

**Comment by fa1c0nx** [comment]
Alright sweet, thx!
