### ISSUE TITLE
You will continue to support?

### ISSUE THREAD

**Issue by C4rt3r** [RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore#6]
You will continue to support?

**Comment by RobyRew** [comment]
> You will continue to support?

Yes, next week i have a couple free-days and im planing to update this and other guides, you would see :)

**Comment by C4rt3r** [comment]
thank you for your work

**Comment by RobyRew** [comment]
I hope this weekend, sorry for your waiting man

**Comment by RobyRew** [comment]
> thank you for your work
didn't happen and now Monterrey and Ventura are not working at all no matter what I do

**Comment by RobyRew** [comment]
> You will continue to support?

Monterrey and Ventura support is added now, test it if you need it
