### ISSUE TITLE
Not booting with last release

### ISSUE THREAD

**Issue by SanoranX** [RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore#7]
The last release is not working for me. I have a bunch of errors upon startup. The picture is below (sry for quality)

The only release that I was managed to start was 0.6.9 but this version does not work with the latest macOS.
![image](https://user-images.githubusercontent.com/51456309/146288422-328b50bb-1dc0-4d5e-a942-77d9318289d2.png)

**Comment by RobyRew** [comment]
Nop, only Big Sur is working, I still didn't managed to have Monterrey or Ventura running they Kernel crash on Booting the OS.

BTW the error you have is because you have enabled ResizeAppleGpuBars on BIOS, disable it.
